### ISSUE TITLE
Cannot create DAX client with session - InvalidParameter: custom handlers not supported

### ISSUE THREAD

**Issue by edulopezTriv** [aws/aws-dax-go#17] opened 2019-09-20 15:49 UTC
I'm trying to create a DAX client with `dax.NewWithSession` using the same session  I use for creating a dynamo client. I can confirm it works with dynamo.

**Sample**

```
sess, err := GetSession()
if err != nil {
	return nil, err
}
if useDAX {
	svc, err = dax.NewWithSession(sess)
} else {
	svc = dynamodb.New(sess)
}
```

this is the error I have when calling `dax.NewWithSession`

```
InvalidParameter: custom handlers not supported
```
If you read the code from `aws-dax-go` that error comes from  ` client.ValidateHandlers`

What should we do to create a new DAX client using our `aws session`?

**Env**

```
github.com/aws/aws-dax-go v1.1.1
github.com/aws/aws-sdk-go v1.19.48
```

**Comment by VasilyFomin** [comment] 2019-11-08 23:51
We indeed do not support custom handlers, but probably a warning will be sufficient, otherwise you'll have to provide/modify a separate session for the Dax client.

Are you providing custom handlers?

**Comment by edulopezTriv** [comment] 2019-11-13 14:45
> We indeed do not support custom handlers, but probably a warning will be sufficient, otherwise you'll have to provide/modify a separate session for the Dax client.
> 
> Are you providing custom handlers?

Nope. I'm just using my session object created with AWS sdk.

I'm worried that ` dax.NewWithSession` has a bug.

**Comment by dspinei** [comment] 2019-11-14 15:22
The error reported by @edulopezTriv  can be reproduced simply with:
```
	sess, _ := session.NewSession()
	return dax.NewWithSession(*sess)
```
Looks like a default Session created with aws-sdk-go already contains handlers that are considered custom by the dax sdk.

Env
```
github.com/aws/aws-dax-go v1.1.4
github.com/aws/aws-sdk-go v1.18.6
```

**Comment by VasilyFomin** [comment] 2019-11-18 23:45
After looking into it somewhat more, I think we're going to deprecate this constructor all together.

The reason we have validations is because DAX doesn't use custom configurations and handlers and we want to make sure a customer is aware of this. Essentially the only fields we're using from the session objects are some of the configurations:

https://github.com/aws/aws-dax-go/blob/19b34c5c99ea4b76610dcbae7d87fd572de012df/dax/service.go#L86-L107

Which essentially means you'll have to modify your existing session anyway, to get it working with DAX, at which point you might as well create a new DAX configuration.

What's your use case when you use an existing session? How do you set the dax endpoint?

**Comment by edulopezTriv** [comment] 2019-11-19 16:00
The thing is I may use that session to any other thing in my project. I rather have a `NewDaxWithCredentials(session)` that takes what it needs from it instead of having to change it.

**Comment by VasilyFomin** [comment] 2019-11-19 22:48
The problem is it wont' work, because you will still have to modify the session's `Endpoint` to point to your dax cluster

**Comment by dspinei** [comment] 2019-11-21 14:20
> you will still have to modify the session's Endpoint to point to your dax cluster
I don't think that's the issue. I think the expectation is that the following code, that is familiar across AWS SDKs, works:
```
sess, _ := session.NewSession(&aws.Config{
	Endpoint: aws.String(daxURL),
	Region:   aws.String(daxRegion),
})
return dax.NewWithSession(*sess)
```

**Comment by lyaoxion** [comment] 2020-04-17 23:40
This was fixed in v1.2.0. Creation of DAX client from a Session will not throw out an error as long as all required configurations is provided in the Session.

**Closed by lyaoxion** 2020-04-17 23:40 UTC

**Comment by hmayi** [comment] 2024-02-09 02:42
@lyaoxion Have you upgraded the DAX client using SDKV2?

**Comment by miparnisari** [comment] 2024-02-09 04:42
@hmayi there is an open PR from the community: https://github.com/aws/aws-dax-go/pull/43

But it hasn't received any attention from the maintainers of DAX. ☹️

**Comment by hmayi** [comment] 2024-02-09 13:02
Thanks for the reply. Were you able to create sessions with SDK1?

Regards
Hiranmayi.
